project/messages/models.py
from project import db
from datetime import datetime

MessageLike = db.Table(
    'likes', db.Column('id', db.Integer, primary_key=True),
    db.Column('message_id', db.Integer,
              db.ForeignKey('messages.id', ondelete="cascade")),
    db.Column('user_id', db.Integer,
              db.ForeignKey('users.id', ondelete="cascade")),
    db.UniqueConstraint('message_id', 'user_id', name="no_multiple_liking"))


class Message(db.Model):

    __tablename__ = 'messages'

    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.String(140))
    timestamp = db.Column(db.DateTime)
    user_id = db.Column(db.Integer,
                        db.ForeignKey('users.id', ondelete='CASCADE'))
    likes = db.relationship(
        "User",
        secondary=MessageLike,
        backref=db.backref('message_likes', lazy='dynamic'),
        lazy='dynamic')

    def __init__(self, text, user_id, timestamp=datetime.utcnow()):
        self.text = text
        self.user_id = user_id
        self.timestamp = timestamp

project/messages/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.widgets import TextArea
from wtforms.validators import DataRequired


class MessageForm(FlaskForm):
    text = StringField('text', validators=[DataRequired()], widget=TextArea())


class LikeForm(FlaskForm):
    pass

project/messages/views.py
from flask import redirect, render_template, request, url_for, Blueprint, flash
from project.messages.models import Message
from project.users.views import ensure_correct_user
from project.users.models import User
from project.messages.forms import MessageForm, LikeForm
from flask_login import current_user, login_required
from project import db
from functools import wraps

messages_blueprint = Blueprint(
    'messages', __name__, template_folder='templates')


def ensure_correct_user(fn):
    @wraps(fn)
    def wrapper(*args, **kwargs):
        if kwargs.get('id') != current_user.id:
            flash({'text': "Not Authorized", 'status': 'danger'})
            return redirect(url_for('root'))
        return fn(*args, **kwargs)

    return wrapper


@messages_blueprint.route('/', methods=["POST"])
@login_required
def index(id):
    if current_user.get_id() == str(id):
        form = MessageForm()
        from IPython import embed
        embed()
        if form.validate():
            new_message = Message(text=form.text.data, user_id=id)
            db.session.add(new_message)
            db.session.commit()
            return redirect(url_for('users.show', id=id))
    return render_template('messages/new.html', form=form)


@messages_blueprint.route('/new')
@login_required
@ensure_correct_user
def new(id):
    return render_template('messages/new.html', form=MessageForm())


@messages_blueprint.route('/<int:message_id>', methods=["GET", "DELETE"])
def show(id, message_id):
    found_message = Message.query.get(message_id)
    if request.method == b"DELETE" and current_user.id == id:
        db.session.delete(found_message)
        db.session.commit()
        return redirect(url_for('users.show', id=id))
    return render_template(
        'messages/show.html', message=found_message, form=LikeForm())


@messages_blueprint.route('/<int:message_id>/like', methods=['POST', 'DELETE'])
@login_required
def like_toggle(id, message_id):
    user = current_user
    form = LikeForm(request.form)
    if request.method == 'POST':
        user.message_likes.append(Message.query.get_or_404(message_id))
        db.session.commit()
        return redirect(url_for('root', id=id, message_id=message_id))
    if request.method == b'DELETE':
        user.message_likes.remove(Message.query.get_or_404(message_id))
        db.session.commit()
        return redirect(url_for('root', id=id, message_id=message_id))
    return redirect(url_for('root'))

project/messages/templates/messages/new.html
{% extends 'base.html' %} 
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-6">
    <form action="{{ url_for('messages.index', id=current_user.id) }}" method="POST">
      {{ form.csrf_token }}
      <div>
        {% if form.text.errors %}
          {% for error in form.text.errors %}
          <span class="text-danger">
            {{ error }}
          </span>
          {% endfor %}
        {% endif %}
        {{ form.text(placeholder="What's happening?", class="form-control", rows="3") }}
      </div>
      <button type="submit" class="btn btn-outline-success btn-block">Add my message!</button>
    </form>
  </div>
</div>
{% endblock %}

project/messages/templates/messages/show.html
{% extends 'base.html' %} 
{% block content %}
<div class="bg"></div>
<div class="row justify-content-center">
  <div class="col-md-6">
    <ul class="list-group no-hover" id="messages">
      <li class="list-group-item">
        <a href="{{ url_for('users.show', id=message.user.id) }}">
          <img src="{{ message.user.image_url }}" alt="" class="timeline-image">
        </a>
        <div class="message-area">
          <div class="message-heading">
            <h6>Niki</h6>
            <a href="{{ url_for('users.show', id=message.user.id) }}">@{{ message.user.username }}</a>
            <span class="text-muted">{{ message.timestamp.strftime('%d %B %Y') }}</span>
            {% if current_user.is_authenticated %}
              {% if current_user.id == message.user.id %}
                <form method="POST" action="{{url_for('messages.show', message_id=message.id, id=message.user.id)}}?_method=DELETE">
                  <input type="submit" value="Delete" class="btn btn-outline-danger">
                </form>
              {% elif current_user.is_following(message.user) %}
                <form method="POST" action="{{url_for('users.follower', follower_id=message.user.id)}}?_method=DELETE">
                  <input type="submit" value="Unfollow" class="btn btn-primary">
                </form>
              {% else %}
                <form method="POST" action="{{url_for('users.follower', follower_id=message.user.id)}}">
                  <input type="submit" value="Follow" class="btn btn-outline-primary btn-sm">
                </form>
              {% endif %}
            {% endif %}
          </div>
          <p class="single-message">{{ message.text }}</p>
          <div class="like">
            {% if current_user in message.likes %}
              <form class='likefull' action="{{ url_for('messages.like_toggle', message_id=message.id, id=message.user.id) }}?_method=DELETE" method='POST'>
                  {{ form.csrf_token }}
                  <button type='submit'><i class="fas fa-heart"></i></button>
              </form>
              <form class="likeempty hidden" action="{{ url_for('messages.like_toggle', message_id=message.id, id=message.user.id) }}" method='POST'>
                  {{ form.csrf_token }}
                  <button type='submit'><i class="far fa-heart"></i></button>
              </form>
            {% else %}
              <form class='likefull hidden' action="{{ url_for('messages.like_toggle', message_id=message.id, id=message.user.id) }}?_method=DELETE" method='POST'>
                  {{ form.csrf_token }}
                  <button type='submit'><i class="fas fa-heart"></i></button>
              </form>
              <form class='likeempty' action="{{ url_for('messages.like_toggle', message_id=message.id, id=message.user.id)  }}" method='POST'>
                  {{ form.csrf_token }}
                <button type='submit'><i class="far fa-heart"></i></button>
              </form>
            {% endif %}
          </div>
        </div>
      </li>
    </ul>
  </div>
</div>
{% endblock %}